apiVersion: capabilities.3scale.net/v1beta1
kind: Backend
metadata:
  name: {{ backend_name }}
spec:
  name: {{ backend_name }}
  privateBaseURL: {{ frontend_url }}
  systemName: {{ backend_name }}
  description: Backend of {{ backend_name }}

  {% if use_custom_tenant|bool %}

  providerAccountRef:
    name: {{ tenant_access_token_secret }}

  {% endif %}
