kind: StorageSystem
apiVersion: odf.openshift.io/v1alpha1
metadata:
  name: {{ odf_name }}
  namespace: openshift-storage
spec:
  kind: storagecluster.ocs.openshift.io/v1
  name: ocs-storagecluster
  namespace: openshift-storage
