---

- name: "deploy threescale  operator in openshift-operators"
  import_role:
    name: ../roles/operator_olm
  vars:
    operator_name: "{{ threescale_operator_packagemanifest }}"
    packagemanifest: "{{ threescale_operator_packagemanifest }}"
    subscription_channel: "{{ threescale_operator_subscription_channel }}"
    subscription_namespace: "openshift-operators"
    subscription_name: "{{ threescale_operator_subscription_name }}"
    automatic_installplan_approval: "{{ threescale_operator_subscription_automatic_installplan_approval }}"
    subscription_starting_csv: "{{ threescale_operator_subscription_starting_csv  }}"
    csv_prefix: "{{ threescale_operator_csv_prefix }}"

- name: "create API Manager custom resource"
  k8s:
    state: present
    name: apimgmr
    namespace: "{{ apimanager_namespace }}"
    definition: "{{ lookup('template', 'templates/'+ threescale_cr_template) | from_yaml }} "

- name: "wait until threescale system-app deployment is active in {{ apimanager_namespace }}"
  shell: "{{ openshift_cli }} get dc system-app -o template --template={{ json_template }} -n {{ apimanager_namespace }}"
  vars:
    json_template: '\{\{.status.readyReplicas\}\}'
  register: result
  until: result.stdout == "1"
  retries: 10
  delay: 30
  changed_when: false
