---

- name: "delete APIManager custom resource"
  k8s:
    state: absent
    kind: APIManager
    api_version: apps.3scale.net/v1alpha1
    name: apimanager
    namespace: "{{ namespace }}"
  when: undeploy_api_manager is defined and undeploy_api_manager == "true"

- name: "delete {{ threescale_operator_packagemanifest }}  operator in {{ apimanager_namespace }}"
  import_role:
    name: ../roles/operator_olm
    tasks_from: uninstall
  vars:
    operator_name: "{{ threescale_operator_packagemanifest }}"
    subscription_namespace: "{{ apimanager_namespace }}"
    subscription_name: "{{ threescale_operator_subscription_name }}"
    csv_prefix: "{{ threescale_operator_csv_prefix }}"
  when: undeploy_api_manager is defined and undeploy_api_manager == "true"

- name: "delete operatorgroup from {{ apimanager_namespace }} namespace"
  import_role:
    name: ../roles/operatorgroup
    tasks_from: uninstall
  vars:
    operatorgroup_name: "{{ apimanager_namespace }}"
    operatorgroup_namespace: "{{ apimanager_namespace }}"
  when: undeploy_api_manager is defined and undeploy_api_manager == "true"

- name: "delete namespace {{ apimanager_namespace }}"
  k8s:
    state: absent
    name: "{{ apimanager_namespace }}"
    kind: Project
    api_version: project.openshift.io/v1
  when: undeploy_api_manager is defined and undeploy_api_manager == "true"
