---

- name: Deploy API tenant resources
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/all.yml

  tasks:
    - include: tasks/api_tenant.yml
