---

- name: Deploy all quickstart resources
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/all.yml
  vars:
    ACTION: install

  tasks:
  - include: tasks/sso.yml
#  - include: tasks/odf.yml
#  - include: tasks/api_manager.yml
  - include: tasks/api_tenant.yml
