# sub 
# fhir-server-test/fhir-server-test1
#*PublicBaseURL
#*issuerEndpoint
#backendUsage.fhir-server-backend-test
#applicationPlans.fhir-oidc-plan

kind: Product
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: fhir-server-test
spec:
  name: fhir-server-test
  systemName: fhir-server-test
  methods:
    get:
      friendlyName: GET
    post:
      friendlyName: POST
    delete:
      friendlyName: DELETE
    put:
      friendlyName: PUT
  mappingRules:
    - httpMethod: GET
      pattern: "/"
      increment: 1
      metricMethodRef: get
    - httpMethod: POST
      pattern: "/"
      increment: 1
      metricMethodRef: post      
    - httpMethod: DELETE
      pattern: "/"
      increment: 1
      metricMethodRef: delete
    - httpMethod: PUT
      pattern: "/"
      increment: 1
      metricMethodRef: put         
  deployment:
    apicastHosted: 
    # if it's self-managed, need following lines instead
    # apicastSelfManaged:
    #   stagingPublicBaseURL: https://fhir-fhir-server-3scale-apicast-staging.apps.md-gh-rh-rosa-2.66u6.p1.openshiftapps.com:443
    #   productionPublicBaseURL: https://fhir-fhir-server-3scale-apicast-production.apps.md-gh-rh-rosa-2.66u6.p1.openshiftapps.com:443
      authentication:
        oidc:
          issuerEndpoint: https://zync-sso:XXXXX@keycloak-redhat-rhoam-user-sso.apps.md-gh-rh-rosa-2.66u6.p1.openshiftapps.com/auth/realms/daybreak
          issuerType: keycloak
          credentials: headers
          authenticationFlow:
            standardFlowEnabled: true
            implicitFlowEnabled: false
            serviceAccountsEnabled: false
            directAccessGrantsEnabled: false
  backendUsages:
    fhir-server-backend-test:
      path: /
  applicationPlans:
    fhir-oidc-plan:
      appsRequireApproval: false
      published: true
  policies:
  - configuration:
      allow_headers:
      - authorization
      - content-type
      - x-requested-with
      allow_credentials: true
      allow_methods:
      - GET
      - OPTIONS
      - POST
      - DELETE
      - PUT
      allow_origin: "*"
    enabled: true
    name: cors
    version: builtin  
  - configuration: {}
    enabled: true
    name: apicast
    version: builtin  
  # {% if use_custom_tenant|bool %}

  # providerAccountRef:
  #   name: {{ tenant_access_token_secret }}

  # {% endif %}

  # TODO
  # Developer Audience
  #promoting configuration -- promoting to stage may already be happening every time CR is updated